#code generated by chatGPT4
#reads GEQDSK file


import numpy as np

# Function to split a line into fixed-width chunks
def split_fixed_width(line, width=16):
    return [line[i:i + width] for i in range(0, len(line), width)]

# Function to split a line into Fortran-style chunks
def split_fortran(line):
    return [line[i:i + 16] for i in range(0, len(line.rstrip()), 16)]


def read_geqdsk(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()
        
    # Read header
    header = lines[0].split()
    nw, nh = int(header[5]), int(header[6])


    # Read data values
    data = np.fromiter((float(val) for line in lines[1:] for val in split_fortran(line) if val.strip()), dtype=float)
    
    # Store data in a dictionary
    geqdsk_data = {}
    geqdsk_data['nw'], geqdsk_data['nh'] = nw, nh
    geqdsk_data['rdim'], geqdsk_data['zdim'] = data[0], data[1]
    geqdsk_data['rcentr'], geqdsk_data['rleft'] = data[2], data[3]
    geqdsk_data['zmid'] = data[4]
    geqdsk_data['rmaxis'], geqdsk_data['zmaxis'] = data[5], data[6]
    geqdsk_data['simag'], geqdsk_data['sibry'] = data[7], data[8]
    geqdsk_data['bcentr'] = data[9]
    geqdsk_data['current'] = data[10]
    
    idx = 11
    geqdsk_data['fpol'] = data[idx:idx+nw]
    idx += nw
    geqdsk_data['pres'] = data[idx:idx+nw]
    idx += nw
    geqdsk_data['qpsi'] = data[idx:idx+nw]
    idx += nw
    geqdsk_data['psirz'] = data[idx:idx+(nw*nh)].reshape(nw, nh)
    idx += nw * nh
    geqdsk_data['pprime'] = data[idx:idx+nw]
    idx += nw
    geqdsk_data['ffprime'] = data[idx:idx+nw]
    
    return geqdsk_data


# Read GEQDSK file
file_path = 'g204118.01004'
geqdsk_data = read_geqdsk(file_path)